apiVersion: v1
kind: PersistentVolume
metadata:
  name: datasets-lsst-lsp-int-dax
  annotations:
    volume.beta.kubernetes.io/mount-options: local_lock=all
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1100Ti
  nfs:
    path: /user/precursor_data/datasets
    server: lsst-nfs.ncsa.illinois.edu
  persistentVolumeReclaimPolicy: Retain
