apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-lsst-lsp-int-dax
  annotations:
    volume.beta.kubernetes.io/mount-options: local_lock=all
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1100Ti
  nfs:
    path: /project/hsc/gen3repo
    server: lsst-nfs.ncsa.illinois.edu
  persistentVolumeReclaimPolicy: Retain
